// Service page content — single source of truth for every individual service page.
//
// The dynamic route /services/[slug] reads this config and renders the shared template.
// Add a new service page: add one entry here (and flip live:true in config/services.ts).
//
// `hasCustomPage: true` marks services that already have a hand-built static page under
// src/app/services/<slug>/ — those are excluded from the [slug] template (the static
// folder takes precedence) but still appear on the /services index hub.

export type ProcessStep = { step: string; title: string; description: string };
export type FAQItem = { question: string; answer: string };

export type ServiceContent = {
  slug: string;
  href: string;
  label: string;
  category: string;
  headline: string; // H1 — keyword-rich
  subheadline: string; // one-line hero subtext
  seoTitle: string;
  seoDescription: string;
  focusKeyword: string;
  secondaryKeywords?: string[];
  price: string | null; // null => "Contact us"
  isContactOnly?: boolean; // Enterprise => never show a price
  deliveryTime: string;
  heroDescription: string; // 2–3 sentences, focus keyword in first sentence
  whatYouGet: string[];
  useCases: string[];
  differentiator?: string; // service-specific "why us" card (prepended to defaults)
  process?: ProcessStep[]; // optional override of DEFAULT_PROCESS
  faq: FAQItem[];
  relatedServices: string[];
  jsonLdServiceType: string;
  hasCustomPage?: boolean;
};

export const SITE_URL = "https://digitalstudiolf.online";

// --- Per-category accent colors (literal class strings so Tailwind detects them) ---
export type Accent = {
  text: string;
  bg: string;
  border: string;
  hoverBorder: string;
  gradient: string;
  ring: string;
};

export const categoryAccent: Record<string, Accent> = {
  Websites: {
    text: "text-orange-400",
    bg: "bg-orange-500/10",
    border: "border-orange-500/30",
    hoverBorder: "hover:border-orange-500/30",
    gradient: "from-orange-500 to-orange-600",
    ring: "focus-visible:ring-orange-500/60",
  },
  "E-Commerce": {
    text: "text-emerald-400",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/30",
    hoverBorder: "hover:border-emerald-500/30",
    gradient: "from-emerald-500 to-emerald-600",
    ring: "focus-visible:ring-emerald-500/60",
  },
  "Dashboards & Portals": {
    text: "text-blue-400",
    bg: "bg-blue-500/10",
    border: "border-blue-500/30",
    hoverBorder: "hover:border-blue-500/30",
    gradient: "from-blue-500 to-blue-600",
    ring: "focus-visible:ring-blue-500/60",
  },
  "CRM & Business Systems": {
    text: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/30",
    hoverBorder: "hover:border-amber-500/30",
    gradient: "from-amber-500 to-amber-600",
    ring: "focus-visible:ring-amber-500/60",
  },
  "Booking & Reservations": {
    text: "text-rose-400",
    bg: "bg-rose-500/10",
    border: "border-rose-500/30",
    hoverBorder: "hover:border-rose-500/30",
    gradient: "from-rose-500 to-rose-600",
    ring: "focus-visible:ring-rose-500/60",
  },
  "AI & Automation": {
    text: "text-purple-400",
    bg: "bg-purple-500/10",
    border: "border-purple-500/30",
    hoverBorder: "hover:border-purple-500/30",
    gradient: "from-purple-500 to-purple-600",
    ring: "focus-visible:ring-purple-500/60",
  },
  Authentication: {
    text: "text-cyan-400",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/30",
    hoverBorder: "hover:border-cyan-500/30",
    gradient: "from-cyan-500 to-cyan-600",
    ring: "focus-visible:ring-cyan-500/60",
  },
  "Niche / Special": {
    text: "text-pink-400",
    bg: "bg-pink-500/10",
    border: "border-pink-500/30",
    hoverBorder: "hover:border-pink-500/30",
    gradient: "from-pink-500 to-pink-600",
    ring: "focus-visible:ring-pink-500/60",
  },
  Enterprise: {
    text: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/30",
    hoverBorder: "hover:border-amber-500/30",
    gradient: "from-amber-500 to-amber-600",
    ring: "focus-visible:ring-amber-500/60",
  },
};

export const DEFAULT_ACCENT: Accent = categoryAccent["Websites"];

export function getAccent(category: string): Accent {
  return categoryAccent[category] ?? DEFAULT_ACCENT;
}

export const DEFAULT_PROCESS: ProcessStep[] = [
  { step: "01", title: "Discovery call", description: "We learn your goals, audience, and requirements on a free 30-minute call — no obligation." },
  { step: "02", title: "Proposal & quote", description: "You receive a fixed-price proposal with scope, timeline, and deliverables within 24 hours." },
  { step: "03", title: "Build", description: "We design and develop in short iterations with regular previews and 2–3 revision rounds." },
  { step: "04", title: "Launch & support", description: "We deploy, hand over the code, and include 30 days of free post-launch support." },
];

export const DEFAULT_WHY: string[] = [
  "Direct communication — you work straight with the developer, no account managers or middlemen.",
  "Fast delivery — most projects ship in 7–21 days, not months.",
  "Fixed pricing — agreed upfront, so there are no surprise invoices.",
];

// ─────────────────────────────────────────────────────────────────────────────
//  SERVICE CONTENT
// ─────────────────────────────────────────────────────────────────────────────

export const servicesContent: ServiceContent[] = [
  // ───── WEBSITES (custom pages kept: landing-pages, business-websites) ─────
  {
    slug: "landing-pages",
    href: "/services/landing-pages",
    label: "Landing Pages",
    category: "Websites",
    headline: "High-Converting Landing Pages Built to Turn Visitors Into Clients",
    subheadline: "Fast, focused, conversion-optimised landing pages — delivered in 7 days.",
    seoTitle: "Landing Page Design Service | Digital Studio LF",
    seoDescription: "Professional landing page design service. High-converting, SEO-ready pages delivered in 7 days. Start your project today.",
    focusKeyword: "landing page design service",
    secondaryKeywords: ["high converting landing page", "landing page designer for hire", "custom landing page development", "landing page design Morocco", "sales page design service", "landing page for Google Ads"],
    price: "From $250",
    deliveryTime: "7 days",
    heroDescription: "Our landing page design service builds fast, focused pages engineered to convert. Every section guides visitors toward one clear action — book, buy, or sign up.",
    whatYouGet: ["Conversion-focused custom design", "Lead capture form wired to your inbox/CRM", "Mobile-first responsive layout", "Sub-2s load speed", "A/B-test ready structure", "SEO basics + analytics"],
    useCases: ["Product launches", "Free-consultation offers", "Paid ad destinations", "Event signups", "Lead-gen campaigns"],
    faq: [
      { question: "How long does it take to build a landing page?", answer: "Standard landing pages ship in 7 days from brief and deposit. Rush delivery is available." },
      { question: "What's the difference between a landing page and a website?", answer: "A landing page is a single focused page built around one goal; a website has multiple pages for browsing. Landing pages convert better for campaigns." },
      { question: "Can I edit it myself afterwards?", answer: "Yes — we can build on a CMS or hand over editable code, plus 30 days of free edits." },
      { question: "Do you build in French and Arabic?", answer: "Yes, in English, French, and Arabic, with proper hreflang for multilingual audiences." },
    ],
    relatedServices: ["business-websites", "login-pages", "crm-systems"],
    jsonLdServiceType: "Landing Page Design",
    hasCustomPage: true,
  },
  {
    slug: "business-websites",
    href: "/services/business-websites",
    label: "Business Websites",
    category: "Websites",
    headline: "Professional Business Websites That Build Trust and Drive Enquiries",
    subheadline: "5–8 page websites that represent your brand and convert visitors.",
    seoTitle: "Business Website Development | Digital Studio LF",
    seoDescription: "Professional business website development. 5–8 page, mobile-responsive, SEO-ready sites that build trust and drive enquiries.",
    focusKeyword: "business website development",
    secondaryKeywords: ["small business website design", "professional company website", "affordable business website", "business website design Morocco", "company website developer", "SEO-ready business website"],
    price: "From $700",
    deliveryTime: "10–14 days",
    heroDescription: "Our business website development gives small and growing companies a professional online presence that builds trust and turns visitors into enquiries.",
    whatYouGet: ["5–8 custom-designed pages", "Contact + enquiry forms", "Mobile-responsive build", "On-page SEO foundations", "Fast, secure hosting setup", "Self-edit CMS option"],
    useCases: ["Accountants & consultants", "Local service businesses", "Professional firms", "Local shops", "B2B suppliers"],
    faq: [
      { question: "Do you handle hosting?", answer: "Yes — we set up fast, secure hosting and can manage it for you or hand it over." },
      { question: "Will it rank on Google?", answer: "We build SEO-ready foundations (structure, speed, schema). Ranking also depends on content and backlinks, which we can advise on." },
      { question: "Can I update it myself?", answer: "Yes — we can build on a CMS so you can edit text and images without touching code." },
      { question: "How long does it take?", answer: "Most business websites are delivered in 10–14 days." },
    ],
    relatedServices: ["landing-pages", "admin-dashboards", "crm-systems"],
    jsonLdServiceType: "Business Website Development",
    hasCustomPage: true,
  },
  {
    slug: "corporate-websites",
    href: "/services/corporate-websites",
    label: "Corporate Websites",
    category: "Websites",
    headline: "Corporate Websites That Reflect Professionalism and Drive Business Growth",
    subheadline: "Polished, brand-consistent multi-page sites for established companies.",
    seoTitle: "Corporate Website Design & Development | Digital Studio LF",
    seoDescription: "Corporate website design and development for established firms. Brand-consistent, multi-page sites with case studies and team sections.",
    focusKeyword: "corporate website design",
    secondaryKeywords: ["corporate web development company", "professional corporate site design", "corporate website redesign", "corporate website agency Morocco", "multi-page company website"],
    price: null,
    deliveryTime: "14–21 days",
    heroDescription: "Our corporate website design gives mid-size companies and professional firms a polished, brand-consistent presence that reinforces credibility with clients, partners, and investors.",
    whatYouGet: ["Multi-page information architecture", "About, team & leadership sections", "Case studies / client work", "Brand-consistent design system", "News / press area", "On-page SEO + analytics"],
    useCases: ["Law firms", "Financial & consulting firms", "HR companies", "Mid-size corporates", "Professional groups"],
    faq: [
      { question: "Can you match our existing brand guidelines?", answer: "Yes — we work from your brand assets to keep typography, colour, and tone fully consistent." },
      { question: "Do you support multiple languages?", answer: "Yes, including English, French, and Arabic with proper hreflang setup." },
      { question: "Can you migrate our current site?", answer: "Yes — we migrate content and set up redirects to preserve your SEO." },
      { question: "Do you offer ongoing maintenance?", answer: "Yes, optional monthly maintenance and content-update plans are available." },
    ],
    relatedServices: ["business-websites", "employee-portals", "crm-systems"],
    jsonLdServiceType: "Corporate Website Design",
  },
  {
    slug: "portfolio-websites",
    href: "/services/portfolio-websites",
    label: "Portfolio Websites",
    category: "Websites",
    headline: "Portfolio Websites That Showcase Your Work and Win New Clients",
    subheadline: "Fast, image-optimised portfolios that make your work the hero.",
    seoTitle: "Portfolio Website Design for Creatives | Digital Studio LF",
    seoDescription: "Portfolio website design for creatives — fast, image-optimised galleries that showcase your work, delivered in 7–10 days. Get a free quote today.",
    focusKeyword: "portfolio website design",
    secondaryKeywords: ["portfolio site for photographers", "personal portfolio website developer", "creative portfolio web design", "portfolio website with CMS", "architect portfolio website design"],
    price: null,
    deliveryTime: "7–10 days",
    heroDescription: "Our portfolio website design puts your work front and centre with fast, image-optimised galleries that turn browsers into clients. Built for designers, photographers, architects, and studios.",
    whatYouGet: ["Project gallery with case studies", "Image optimisation (WebP, lazy-load)", "About & contact pages", "Fast-loading, responsive build", "Optional CMS for new projects", "On-page SEO foundations"],
    useCases: ["Designers & illustrators", "Photographers", "Architects", "Developers", "Creative studios & agencies"],
    faq: [
      { question: "Can I add new projects myself?", answer: "Yes — we can build a simple CMS so you can publish new work without a developer." },
      { question: "Will my images stay sharp but load fast?", answer: "Yes — we serve optimised WebP with lazy-loading so quality stays high and pages stay fast." },
      { question: "Do you design for photographers specifically?", answer: "Yes — we tune galleries, lightboxes, and loading for image-heavy creative work." },
      { question: "How long does it take?", answer: "Most portfolio sites ship in 7–10 days." },
    ],
    relatedServices: ["landing-pages", "business-websites", "login-pages"],
    jsonLdServiceType: "Portfolio Website Design",
  },
  {
    slug: "restaurant-websites",
    href: "/services/restaurant-websites",
    label: "Restaurant Websites",
    category: "Websites",
    headline: "Restaurant Websites with Online Menus, Reservations, and Google Rankings",
    subheadline: "Mobile-first sites that get diners from search to your table.",
    seoTitle: "Restaurant Website Design & Development | Digital Studio LF",
    seoDescription: "Restaurant website design with online menus, reservations, and maps. Mobile-first sites that rank locally and fill tables.",
    focusKeyword: "restaurant website design",
    secondaryKeywords: ["restaurant web design agency", "website with online menu", "restaurant website Marrakech", "cafe website design", "restaurant website with reservations", "local SEO for restaurants"],
    price: null,
    deliveryTime: "7–14 days",
    heroDescription: "Our restaurant website design gives cafes and restaurants a mobile-first site with online menus, reservations, and local Google visibility — so diners find you and book directly.",
    whatYouGet: ["Digital menu display", "Reservation / booking integration", "Google Maps & local SEO", "Photo gallery", "Mobile-first responsive design", "Multilingual (EN/FR/AR)"],
    useCases: ["Marrakesh restaurants", "Cafes & bakeries", "Catering companies", "Dark / cloud kitchens", "Food delivery brands"],
    faq: [
      { question: "Can guests book a table online?", answer: "Yes — we integrate a reservation system so diners can book directly from your site." },
      { question: "Will it show up on Google Maps?", answer: "We set up local SEO and Maps integration to improve your local visibility." },
      { question: "Can I update the menu myself?", answer: "Yes — we can make the menu editable so you can change items and prices anytime." },
      { question: "Do you build in French and Arabic?", answer: "Yes, multilingual restaurant sites are a specialty for the Moroccan market." },
    ],
    relatedServices: ["restaurant-reservations", "landing-pages", "booking-websites-for-hotels"],
    jsonLdServiceType: "Restaurant Website Design",
  },
  {
    slug: "hotel-riad-websites",
    href: "/services/hotel-riad-websites",
    label: "Hotel & Riad Websites",
    category: "Websites",
    headline: "Hotel and Riad Websites That Take Direct Bookings and Cut Booking.com Fees",
    subheadline: "Direct-booking sites that recover the margin OTAs take from you.",
    seoTitle: "Hotel & Riad Website with Direct Booking | Digital Studio LF",
    seoDescription: "Hotel and riad website design with direct booking. Cut Booking.com commission, take direct reservations, and own your guest relationships.",
    focusKeyword: "hotel riad website direct booking",
    secondaryKeywords: ["riad website design Marrakech", "hotel website with booking engine", "boutique hotel web design", "direct booking website for riads", "hotel website design Morocco", "commission-free hotel bookings"],
    price: null,
    deliveryTime: "14–21 days",
    heroDescription: "Our hotel and riad website design with direct booking lets you take reservations on your own site and stop paying 15–20% commission to OTAs. A direct booking site typically pays for itself in 2–3 months.",
    whatYouGet: ["Direct booking system", "Room gallery & descriptions", "Availability calendar", "Online payment integration", "Multilingual (EN/FR/AR)", "Local + worldwide SEO"],
    useCases: ["Marrakesh riads", "Fes medina hotels", "Boutique hotels in Europe", "Guesthouses & B&Bs", "Resorts"],
    differentiator: "No Booking.com commission — you keep 100% of every direct reservation.",
    faq: [
      { question: "How does a direct booking site save me money?", answer: "OTAs charge 15–20% per booking. A direct booking site captures those reservations commission-free, usually paying for itself in 2–3 months." },
      { question: "Can guests pay online?", answer: "Yes — we integrate secure online payment and instant booking confirmation." },
      { question: "Is it multilingual?", answer: "Yes — English, French, and Arabic, ideal for Moroccan riads serving international guests." },
      { question: "Can it sync availability?", answer: "Yes — we can connect an availability calendar and optional channel sync." },
    ],
    relatedServices: ["hotel-booking-systems", "crm-for-travel-agencies", "booking-websites-for-hotels"],
    jsonLdServiceType: "Hotel & Riad Website Development",
  },
  {
    slug: "real-estate-websites",
    href: "/services/real-estate-websites",
    label: "Real Estate Websites",
    category: "Websites",
    headline: "Real Estate Websites with Property Listings, Lead Capture, and CRM",
    subheadline: "Searchable listing sites that turn property views into leads.",
    seoTitle: "Real Estate Website Development | Digital Studio LF",
    seoDescription: "Real estate website development with property listings, search filters, lead capture, and CRM integration for agents and developers.",
    focusKeyword: "real estate website development",
    secondaryKeywords: ["real estate web design agency", "property listing website development", "real estate website Morocco", "property search website with filters", "website for real estate agents", "real estate lead generation website"],
    price: null,
    deliveryTime: "14–21 days",
    heroDescription: "Our real estate website development gives agents and developers a searchable, lead-generating listing site with map search, filters, and CRM integration to capture and follow up every enquiry.",
    whatYouGet: ["Property listing pages", "Search & filter by criteria", "Map-based search", "Lead capture forms", "CRM integration", "Agent / agency profiles"],
    useCases: ["Moroccan real estate agencies", "International property listings", "Property developers", "Letting agents", "Property managers"],
    faq: [
      { question: "Can clients search and filter properties?", answer: "Yes — buyers can filter by price, location, type, and features, with map-based search." },
      { question: "Does it connect to a CRM?", answer: "Yes — leads flow straight into a CRM so nothing falls through the cracks." },
      { question: "Can I add and remove listings myself?", answer: "Yes — we build an admin area so you manage listings without a developer." },
      { question: "Can it handle international listings?", answer: "Yes — multi-currency and multilingual listings are supported." },
    ],
    relatedServices: ["crm-systems", "landing-pages", "lead-management"],
    jsonLdServiceType: "Real Estate Website Development",
  },
  {
    slug: "medical-websites",
    href: "/services/medical-websites",
    label: "Medical & Dental Sites",
    category: "Websites",
    headline: "Medical and Dental Websites That Build Patient Trust and Grow Bookings",
    subheadline: "Clean, trustworthy clinic sites with online appointment booking.",
    seoTitle: "Medical & Dental Website Design | Digital Studio LF",
    seoDescription: "Medical and dental website design with appointment booking, doctor profiles, and secure contact. Build patient trust and grow bookings.",
    focusKeyword: "medical dental website design",
    secondaryKeywords: ["dental clinic website design", "medical practice web design", "doctor website with appointment booking", "clinic website Morocco", "healthcare website development", "physiotherapy website design"],
    price: null,
    deliveryTime: "10–14 days",
    heroDescription: "Our medical and dental website design helps clinics build patient trust and grow bookings with clear service pages, doctor profiles, and online appointment scheduling.",
    whatYouGet: ["Online appointment booking", "Service & treatment pages", "Doctor / staff profiles", "Secure contact forms", "Mobile-first responsive design", "Local SEO setup"],
    useCases: ["Clinics in Morocco", "Dental practices", "Physiotherapy", "Dermatology & aesthetics", "Specialist consultants"],
    faq: [
      { question: "Can patients book appointments online?", answer: "Yes — we integrate a booking system with reminders to reduce no-shows." },
      { question: "Is patient contact data handled securely?", answer: "Yes — forms use secure transmission and we follow privacy best practices." },
      { question: "Can you list multiple doctors and services?", answer: "Yes — each practitioner and treatment gets its own profile and page." },
      { question: "Do you build in French and Arabic?", answer: "Yes, multilingual clinic sites are fully supported." },
    ],
    relatedServices: ["appointment-booking", "landing-pages", "business-websites"],
    jsonLdServiceType: "Medical & Dental Website Design",
  },
  {
    slug: "law-firm-websites",
    href: "/services/law-firm-websites",
    label: "Law Firm Websites",
    category: "Websites",
    headline: "Law Firm Websites That Establish Authority and Generate Client Enquiries",
    subheadline: "Authoritative, trust-building sites for legal practices.",
    seoTitle: "Law Firm Website Design & Development | Digital Studio LF",
    seoDescription: "Law firm website design with practice-area pages, attorney profiles, and consultation forms that establish authority and generate enquiries.",
    focusKeyword: "law firm website design",
    secondaryKeywords: ["attorney website design", "legal website development", "lawyer website with consultation form", "law firm web design Morocco", "notary website design"],
    price: null,
    deliveryTime: "14–21 days",
    heroDescription: "Our law firm website design establishes authority and generates qualified enquiries with clear practice-area pages, attorney profiles, and trust signals that reassure prospective clients.",
    whatYouGet: ["Practice-area pages", "Attorney / partner profiles", "Consultation request forms", "Trust signals & credentials", "Professional, restrained design", "On-page SEO foundations"],
    useCases: ["Moroccan law firms", "International legal practices", "Notaries", "Legal consultants", "Boutique chambers"],
    faq: [
      { question: "Can each practice area have its own page?", answer: "Yes — dedicated pages per practice area improve clarity and SEO." },
      { question: "Can prospective clients request a consultation?", answer: "Yes — we add secure consultation request forms that route to your inbox." },
      { question: "Do you support multiple languages?", answer: "Yes — English, French, and Arabic for firms serving mixed clientele." },
      { question: "How long does it take?", answer: "Most law firm sites are delivered in 14–21 days." },
    ],
    relatedServices: ["business-websites", "crm-systems", "landing-pages"],
    jsonLdServiceType: "Law Firm Website Design",
  },
  {
    slug: "educational-websites",
    href: "/services/educational-websites",
    label: "Educational Websites",
    category: "Websites",
    headline: "Educational Websites for Schools, Courses, and Online Learning Platforms",
    subheadline: "Sites for schools and course creators with enrollment and portals.",
    seoTitle: "Educational Website Design & Development | Digital Studio LF",
    seoDescription: "Educational website development for schools, tutors, and course creators. Course pages, student portals, and online enrollment.",
    focusKeyword: "educational website development",
    secondaryKeywords: ["school website design", "e-learning website development", "course website with enrollment", "training center website Morocco", "language school web design", "student portal development"],
    price: null,
    deliveryTime: "14–21 days",
    heroDescription: "Our educational website development helps schools, tutors, and course creators present programs clearly and enroll students online, with optional student portals and content management.",
    whatYouGet: ["Course / program pages", "Online enrollment forms", "Optional student portal", "Content management system", "Mobile-first responsive design", "Local + program SEO"],
    useCases: ["Moroccan schools", "Language schools", "Online tutors", "Coaching programs", "Training centers"],
    faq: [
      { question: "Can students enroll online?", answer: "Yes — we add enrollment forms and can connect payment for paid courses." },
      { question: "Do you build student portals?", answer: "Yes — optional login areas for materials, progress, and announcements." },
      { question: "Can staff update content?", answer: "Yes — a CMS lets staff edit courses and news without a developer." },
      { question: "Is it multilingual?", answer: "Yes — English, French, and Arabic are supported." },
    ],
    relatedServices: ["user-portals", "login-pages", "crm-systems"],
    jsonLdServiceType: "Educational Website Development",
  },

  // ───── E-COMMERCE ─────
  {
    slug: "online-stores",
    href: "/services/online-stores",
    label: "Online Stores",
    category: "E-Commerce",
    headline: "Custom Online Stores Built to Sell — Not Just Look Good",
    subheadline: "Fast, conversion-focused stores with secure checkout.",
    seoTitle: "Custom Online Store Development | Digital Studio LF",
    seoDescription: "Custom online store development with product pages, cart, secure checkout, and inventory. Fast, conversion-focused e-commerce that sells.",
    focusKeyword: "custom online store development",
    secondaryKeywords: ["e-commerce website development", "online shop design Morocco", "custom ecommerce developer", "online store with payment gateway", "mobile-first ecommerce website", "ecommerce website for small business"],
    price: null,
    deliveryTime: "14–28 days",
    heroDescription: "Our custom online store development builds fast, conversion-focused e-commerce with smooth product browsing, secure checkout, and inventory management — designed to sell, not just look good.",
    whatYouGet: ["Product catalog & pages", "Cart & secure checkout", "Payment gateway integration", "Inventory management", "Order & customer admin", "Mobile-first, fast storefront"],
    useCases: ["Moroccan artisans", "Fashion brands", "Beauty & cosmetics", "DTC startups", "Specialty retailers"],
    faq: [
      { question: "Which payment methods can you integrate?", answer: "We integrate major gateways and local options depending on your market." },
      { question: "Can I manage products and orders myself?", answer: "Yes — a clean admin area lets you manage catalog, stock, and orders." },
      { question: "Is the store fast on mobile?", answer: "Yes — we build mobile-first with optimised images and code for fast checkout." },
      { question: "Can it scale as I grow?", answer: "Yes — the architecture supports more products, traffic, and features over time." },
    ],
    relatedServices: ["digital-product-stores", "landing-pages", "crm-systems"],
    jsonLdServiceType: "Online Store Development",
  },
  {
    slug: "multi-vendor-marketplaces",
    href: "/services/multi-vendor-marketplaces",
    label: "Multi-vendor Markets",
    category: "E-Commerce",
    headline: "Custom Multi-Vendor Marketplaces Built for Scale",
    subheadline: "Platform businesses with vendor onboarding and commissions.",
    seoTitle: "Multi-Vendor Marketplace Development | Digital Studio LF",
    seoDescription: "Multi-vendor marketplace development with vendor registration, product listings, payments, and commission management. Built to scale.",
    focusKeyword: "multi-vendor marketplace development",
    secondaryKeywords: ["marketplace website development", "multi seller platform development", "custom marketplace builder", "B2B marketplace development", "marketplace with split payments"],
    price: null,
    deliveryTime: "28–60 days",
    heroDescription: "Our multi-vendor marketplace development powers platform businesses where many sellers list products under one roof, with vendor onboarding, split payments, and commission management built in.",
    whatYouGet: ["Vendor registration & dashboards", "Product listing management", "Split payments & payouts", "Commission system", "Buyer storefront & search", "Admin moderation tools"],
    useCases: ["Niche marketplaces", "Local artisan platforms", "B2B marketplaces", "Rental platforms", "Service marketplaces"],
    faq: [
      { question: "Can vendors manage their own products?", answer: "Yes — each vendor gets a dashboard to manage listings, orders, and payouts." },
      { question: "How are commissions handled?", answer: "We build configurable commission rules with automated split payments." },
      { question: "Can I moderate vendors and listings?", answer: "Yes — admin tools let you approve vendors and moderate content." },
      { question: "How long does it take?", answer: "Marketplaces are larger builds, typically 4–8+ weeks depending on scope." },
    ],
    relatedServices: ["online-stores", "crm-systems", "admin-dashboards"],
    jsonLdServiceType: "Marketplace Development",
  },
  {
    slug: "subscription-websites",
    href: "/services/subscription-websites",
    label: "Subscription Sites",
    category: "E-Commerce",
    headline: "Subscription Sites with Recurring Billing, Member Areas, and Automation",
    subheadline: "Recurring-revenue platforms with gated content and member portals.",
    seoTitle: "Subscription Website Development | Digital Studio LF",
    seoDescription: "Subscription website development with recurring billing, member portals, content gating, and automated emails. Build recurring revenue.",
    focusKeyword: "subscription website development",
    secondaryKeywords: ["membership website development", "recurring billing website", "subscription platform developer", "content gating website", "membership site with member portal"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our subscription website development builds recurring-revenue platforms with automated billing, member-only areas, and content gating for membership communities, SaaS, and creators. Every build includes secure payment flows, a self-service member portal, and the admin tools you need to track plans, churn, and revenue from day one — so you launch with a platform that runs itself instead of a site you babysit.",
    whatYouGet: ["Recurring billing integration", "Member portal & accounts", "Content gating by plan", "Automated emails & renewals", "Plan & pricing management", "Churn & revenue admin"],
    useCases: ["Membership communities", "SaaS products", "Content creators", "Online courses", "Subscription boxes"],
    faq: [
      { question: "Which billing providers do you support?", answer: "We integrate leading subscription billing providers with secure recurring payments, so cards are charged automatically each cycle and you never store sensitive payment data yourself." },
      { question: "Can I gate content by plan?", answer: "Yes — content gating is built in, so members only see the pages, downloads, or features their plan includes, and upgrading unlocks more instantly." },
      { question: "Are renewals and dunning automated?", answer: "Yes — renewals, failed-payment retries, and the emails around them are automated, which recovers revenue you would otherwise lose to expired cards." },
      { question: "Can members manage their own plans?", answer: "Yes — a self-service member portal handles upgrades, downgrades, payment-method changes, and cancellations without you lifting a finger." },
      { question: "How do I see how the business is doing?", answer: "An admin area shows active subscribers, plan breakdowns, churn, and recurring revenue at a glance, so decisions are based on real numbers." },
      { question: "Can I start simple and add plans later?", answer: "Yes — plans and pricing are managed from the admin, so you can launch with one tier and introduce annual or premium plans as you grow." },
    ],
    relatedServices: ["login-pages", "crm-systems", "user-portals"],
    jsonLdServiceType: "Subscription Platform Development",
  },
  {
    slug: "digital-product-stores",
    href: "/services/digital-product-stores",
    label: "Digital Product Stores",
    category: "E-Commerce",
    headline: "Digital Product Stores That Deliver Downloads, Templates, and Courses Instantly",
    subheadline: "Sell downloads with instant delivery and license control.",
    seoTitle: "Digital Product Store Development | Digital Studio LF",
    seoDescription: "Digital product store development with instant delivery, license management, payments, and upsells. Sell downloads, templates, and courses.",
    focusKeyword: "digital product store development",
    secondaryKeywords: ["sell digital downloads website", "digital download store development", "website to sell templates and courses", "instant delivery ecommerce", "license key store development"],
    price: null,
    deliveryTime: "14–28 days",
    heroDescription: "Our digital product store development lets you sell downloads, templates, and courses with instant delivery, license management, and upsells — no manual fulfilment.",
    whatYouGet: ["Instant digital delivery", "License key management", "Payment integration", "Upsells & order bumps", "Customer download area", "Sales & revenue admin"],
    useCases: ["Designers selling templates", "Developers selling code", "Educators selling courses", "Stock asset sellers", "eBook & guide authors"],
    faq: [
      { question: "Is delivery automatic after payment?", answer: "Yes — customers get instant download access or license keys after checkout." },
      { question: "Can I sell licenses?", answer: "Yes — we support license key generation and management." },
      { question: "Can I add upsells?", answer: "Yes — order bumps and upsells increase average order value." },
      { question: "Where do customers access purchases?", answer: "Each customer gets a secure account with their downloads and licenses." },
    ],
    relatedServices: ["online-stores", "subscription-websites", "landing-pages"],
    jsonLdServiceType: "Digital Product Store Development",
  },

  // ───── DASHBOARDS & PORTALS (custom: admin-dashboards) ─────
  {
    slug: "admin-dashboards",
    href: "/services/admin-dashboards",
    label: "Admin Dashboards",
    category: "Dashboards & Portals",
    headline: "Custom Admin Dashboards That Give You Full Control of Your Business",
    subheadline: "Real-time data, user management, and role-based access.",
    seoTitle: "Custom Admin Dashboard Development | Digital Studio LF",
    seoDescription: "Custom admin dashboard development with real-time data, analytics, user management, and role-based access control. Delivered fast, built to scale.",
    focusKeyword: "custom admin dashboard development",
    secondaryKeywords: ["admin panel development", "custom dashboard developer", "React admin dashboard development", "business dashboard development", "dashboard with role-based access", "internal tool development"],
    price: "From $1,200",
    deliveryTime: "21–35 days",
    heroDescription: "Our custom admin dashboard development gives you full control of your business with real-time data, user management, and role-based access in one clean interface.",
    whatYouGet: ["Real-time data views", "Role-based access control", "User & content management", "Charts & KPI widgets", "Search, filter & export", "Secure authentication"],
    useCases: ["SaaS products", "Internal ops tools", "Multi-location businesses", "Operations teams", "Marketplaces"],
    faq: [
      { question: "Can you connect it to our existing data?", answer: "Yes — we integrate with your database, APIs, or third-party tools." },
      { question: "Does it support multiple user roles?", answer: "Yes — granular role-based access controls what each user can see and do." },
      { question: "Can we export data?", answer: "Yes — CSV/PDF export and scheduled reports are supported." },
      { question: "How long does it take?", answer: "Most dashboards ship in 3–5 weeks depending on scope." },
    ],
    relatedServices: ["analytics-dashboards", "crm-systems", "reporting-systems"],
    jsonLdServiceType: "Admin Dashboard Development",
    hasCustomPage: true,
  },
  {
    slug: "analytics-dashboards",
    href: "/services/analytics-dashboards",
    label: "Analytics Dashboards",
    category: "Dashboards & Portals",
    headline: "Analytics Dashboards That Turn Your Data Into Clear, Actionable Insights",
    subheadline: "KPI tracking, charts, and real-time reporting in one place.",
    seoTitle: "Custom Analytics Dashboard Development | Digital Studio LF",
    seoDescription: "Analytics dashboard development with KPI tracking, charts, filters, real-time updates, and export. Turn data into decisions.",
    focusKeyword: "analytics dashboard development",
    secondaryKeywords: ["KPI dashboard development", "business intelligence dashboard", "custom data visualization dashboard", "real-time analytics dashboard", "marketing analytics dashboard development"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our analytics dashboard development turns scattered data into clear, actionable insights with KPI tracking, interactive charts, and real-time updates tailored to your business.",
    whatYouGet: ["Custom KPI tracking", "Interactive charts & graphs", "Filters & date ranges", "Real-time data updates", "Export to CSV/PDF", "Multi-source integration"],
    useCases: ["Marketing teams", "Operations", "Executives", "Agencies", "E-commerce analytics"],
    faq: [
      { question: "Can you pull from multiple data sources?", answer: "Yes — we combine databases, APIs, and tools into one dashboard." },
      { question: "Are updates real-time?", answer: "Yes — dashboards can refresh in real time or on a schedule." },
      { question: "Can different teams see different views?", answer: "Yes — role-based views show each team the metrics that matter to them." },
      { question: "Can we export reports?", answer: "Yes — CSV/PDF export and scheduled email reports are supported." },
    ],
    relatedServices: ["admin-dashboards", "reporting-systems", "crm-systems"],
    jsonLdServiceType: "Analytics Dashboard Development",
  },
  {
    slug: "customer-portals",
    href: "/services/customer-portals",
    label: "Customer Portals",
    category: "Dashboards & Portals",
    headline: "Customer Portals That Improve Service and Reduce Support Load",
    subheadline: "Self-service portals for orders, files, invoices, and tickets.",
    seoTitle: "Customer Portal Development | Digital Studio LF",
    seoDescription: "Customer portal development with client login, order history, file sharing, support tickets, and invoices. Improve service, cut support load.",
    focusKeyword: "customer portal development",
    secondaryKeywords: ["client portal development", "self-service portal development", "customer portal with support tickets", "client login area for website", "B2B customer portal development"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our customer portal development gives your clients a secure self-service area for orders, files, invoices, and support — improving service while reducing your support load.",
    whatYouGet: ["Secure client login", "Order & service history", "File sharing & documents", "Support ticket system", "Invoice & payment access", "Notifications"],
    useCases: ["Service businesses", "Agencies", "SaaS products", "Professional firms", "Wholesalers"],
    faq: [
      { question: "Can clients see their order history?", answer: "Yes — clients view past orders, invoices, and documents in one place." },
      { question: "Does it include support tickets?", answer: "Yes — built-in ticketing reduces email back-and-forth." },
      { question: "Is client data secure?", answer: "Yes — secure authentication and role-based access protect client data." },
      { question: "Can it connect to our CRM?", answer: "Yes — portals can integrate with your CRM or back-office systems." },
    ],
    relatedServices: ["login-pages", "crm-systems", "user-portals"],
    jsonLdServiceType: "Customer Portal Development",
  },
  {
    slug: "employee-portals",
    href: "/services/employee-portals",
    label: "Employee Portals",
    category: "Dashboards & Portals",
    headline: "Employee Portals That Streamline Internal Operations and HR",
    subheadline: "One internal hub for HR docs, requests, and announcements.",
    seoTitle: "Employee Portal Development | Digital Studio LF",
    seoDescription: "Employee portal development with HR documents, leave requests, announcements, and task management. Streamline internal operations.",
    focusKeyword: "employee portal development",
    secondaryKeywords: ["intranet development", "internal employee portal development", "HR portal development", "staff portal with leave requests", "company intranet design"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our employee portal development gives your team one internal hub for HR documents, leave requests, announcements, and tasks — replacing scattered emails and spreadsheets.",
    whatYouGet: ["HR document access", "Leave & request workflows", "Company announcements", "Task & project views", "Role-based permissions", "Secure login"],
    useCases: ["Mid-size businesses", "HR teams", "Multi-department companies", "Remote teams", "Operations"],
    faq: [
      { question: "Can employees request leave online?", answer: "Yes — leave requests with approval workflows are built in." },
      { question: "Can we post announcements?", answer: "Yes — company-wide and team announcements with notifications." },
      { question: "Does it handle permissions?", answer: "Yes — role-based access controls what each employee can see." },
      { question: "Can it integrate with HR systems?", answer: "Yes — it can connect to your HR or payroll tools." },
    ],
    relatedServices: ["hr-systems", "admin-dashboards", "crm-systems"],
    jsonLdServiceType: "Employee Portal Development",
  },
  {
    slug: "reporting-systems",
    href: "/services/reporting-systems",
    label: "Reporting Systems",
    category: "Dashboards & Portals",
    headline: "Automated Reporting Systems That Save Hours and Surface the Right Data",
    subheadline: "Scheduled, automated reports with the metrics that matter.",
    seoTitle: "Custom Reporting System Development | Digital Studio LF",
    seoDescription: "Custom reporting system development with scheduled reports, custom metrics, PDF/CSV export, and alerts. Automate reporting and save hours.",
    focusKeyword: "custom reporting system development",
    secondaryKeywords: ["automated reporting software development", "custom report builder development", "scheduled business reports", "reporting dashboard with export", "business reporting automation"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our custom reporting system development automates the reports your team builds by hand, surfacing the right metrics on schedule with PDF/CSV export and alerts.",
    whatYouGet: ["Scheduled automated reports", "Custom metrics & calculations", "PDF / CSV / Excel export", "Threshold alerts", "Multi-source data", "Shareable report links"],
    useCases: ["Operations", "Finance teams", "Marketing", "Agencies", "Executives"],
    faq: [
      { question: "Can reports be scheduled?", answer: "Yes — reports generate and email automatically on your schedule." },
      { question: "Can we define custom metrics?", answer: "Yes — we build the exact calculations your business uses." },
      { question: "Do you support alerts?", answer: "Yes — threshold-based alerts notify you when metrics move." },
      { question: "What formats can we export?", answer: "PDF, CSV, and Excel, plus shareable links." },
    ],
    relatedServices: ["analytics-dashboards", "admin-dashboards", "crm-systems"],
    jsonLdServiceType: "Reporting System Development",
  },

  // ───── CRM & BUSINESS SYSTEMS (custom: crm-systems) ─────
  {
    slug: "crm-systems",
    href: "/services/crm-systems",
    label: "CRM Systems",
    category: "CRM & Business Systems",
    headline: "Custom CRM Systems Built Around Your Business — Not a Generic Template",
    subheadline: "Contact management, pipelines, and automation that fit how you work.",
    seoTitle: "Custom CRM Development for Growing Businesses | Digital Studio LF",
    seoDescription: "Custom CRM development with contact management, pipelines, automation, and reporting — built around your business at a one-time cost.",
    focusKeyword: "custom CRM development",
    secondaryKeywords: ["bespoke CRM development", "custom CRM software company", "CRM with sales pipeline", "affordable custom CRM", "CRM development Morocco", "custom CRM alternative to Salesforce"],
    price: "From $2,500",
    deliveryTime: "28–60 days",
    heroDescription: "Our custom CRM development builds a system around exactly how your business works — contacts, pipelines, automation, and reporting — instead of forcing you into a generic template.",
    whatYouGet: ["Contact & company management", "Custom sales pipelines", "Task & follow-up automation", "Email integration", "Reporting & dashboards", "Role-based access"],
    useCases: ["Agencies", "Real estate", "Travel & hospitality", "Professional services", "Sales teams"],
    differentiator: "One-time cost — no $200/month per-seat fees for features you'll never use.",
    faq: [
      { question: "Why custom instead of Salesforce or HubSpot?", answer: "Generic CRMs charge monthly per seat for features you don't need. A custom CRM does exactly what you need at a one-time cost." },
      { question: "Can it automate follow-ups?", answer: "Yes — automated tasks, reminders, and email sequences keep deals moving." },
      { question: "Can we migrate our existing data?", answer: "Yes — we import contacts and history from spreadsheets or your current CRM." },
      { question: "How long does it take?", answer: "Most CRMs are delivered in 4–8 weeks depending on scope." },
    ],
    relatedServices: ["lead-management", "crm-for-travel-agencies", "admin-dashboards"],
    jsonLdServiceType: "CRM Development",
    hasCustomPage: true,
  },
  {
    slug: "lead-management",
    href: "/services/lead-management",
    label: "Lead Management",
    category: "CRM & Business Systems",
    headline: "Lead Management Systems That Capture, Qualify, and Convert More Leads",
    subheadline: "Capture, score, and follow up every lead automatically.",
    seoTitle: "Lead Management System Development | Digital Studio LF",
    seoDescription: "Lead management system development with capture, scoring, pipeline, follow-up automation, and analytics. Convert more of your leads.",
    focusKeyword: "lead management system development",
    secondaryKeywords: ["lead tracking software development", "custom lead management software", "lead capture and scoring system", "sales pipeline software development", "lead follow-up automation"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our lead management system development captures leads from every channel, scores and qualifies them automatically, and drives timely follow-up so fewer opportunities slip away.",
    whatYouGet: ["Multi-channel lead capture", "Lead scoring & qualification", "Pipeline & stages", "Follow-up automation", "Source & conversion analytics", "Team assignment & routing"],
    useCases: ["Sales teams", "Agencies", "Real estate", "Service businesses", "B2B"],
    faq: [
      { question: "Where can leads come from?", answer: "Forms, landing pages, ads, WhatsApp, email — captured into one system." },
      { question: "How does lead scoring work?", answer: "We define rules that prioritise hot leads so your team works the best ones first." },
      { question: "Can follow-ups be automated?", answer: "Yes — automated reminders and sequences keep every lead nurtured." },
      { question: "Does it integrate with a CRM?", answer: "Yes — it can be standalone or integrated with your CRM." },
    ],
    relatedServices: ["crm-systems", "landing-pages", "email-automation"],
    jsonLdServiceType: "Lead Management System Development",
  },
  {
    slug: "project-management",
    href: "/services/project-management",
    label: "Project Management",
    category: "CRM & Business Systems",
    headline: "Custom Project Management Systems Built for How Your Team Actually Works",
    subheadline: "Tasks, timelines, and client access tailored to your workflow.",
    seoTitle: "Custom Project Management System | Digital Studio LF",
    seoDescription: "Custom project management system development with tasks, timelines, file sharing, team roles, and client access — built around your workflow.",
    focusKeyword: "custom project management system",
    secondaryKeywords: ["custom project management software", "project tracking tool development", "task management system development", "project management tool with client access", "agency project management software"],
    price: null,
    deliveryTime: "28–45 days",
    heroDescription: "Our custom project management system development fits the way your team actually works — tasks, timelines, files, and client access — instead of bending your process to off-the-shelf tools.",
    whatYouGet: ["Tasks & subtasks", "Timelines & milestones", "File sharing", "Team roles & permissions", "Client / guest access", "Progress dashboards"],
    useCases: ["Agencies", "Development teams", "Construction", "Event companies", "Consultancies"],
    faq: [
      { question: "Can clients have limited access?", answer: "Yes — guest access lets clients see progress without internal details." },
      { question: "Does it show timelines?", answer: "Yes — milestones and timelines keep projects on track." },
      { question: "Can we customise workflows?", answer: "Yes — we build the stages and fields your team uses." },
      { question: "Can it integrate with our other tools?", answer: "Yes — it can connect to your CRM, storage, and communication tools." },
    ],
    relatedServices: ["crm-systems", "employee-portals", "admin-dashboards"],
    jsonLdServiceType: "Project Management System Development",
  },
  {
    slug: "inventory-management",
    href: "/services/inventory-management",
    label: "Inventory Management",
    category: "CRM & Business Systems",
    headline: "Inventory Management Systems That Eliminate Stock Surprises",
    subheadline: "Track stock, get low-stock alerts, and manage suppliers.",
    seoTitle: "Custom Inventory Management System | Digital Studio LF",
    seoDescription: "Inventory management system development with stock tracking, low-stock alerts, orders, and supplier management. End stock surprises.",
    focusKeyword: "inventory management system development",
    secondaryKeywords: ["stock management software development", "custom inventory software", "warehouse inventory system", "inventory tracking with low-stock alerts", "multi-location inventory software"],
    price: null,
    deliveryTime: "28–45 days",
    heroDescription: "Our inventory management system development gives you real-time stock visibility, low-stock alerts, and supplier management so you never oversell or run out unexpectedly.",
    whatYouGet: ["Real-time stock tracking", "Low-stock & reorder alerts", "Purchase orders", "Supplier management", "Multi-location support", "Reports & valuation"],
    useCases: ["Retailers", "Manufacturers", "Warehouses", "E-commerce", "Wholesalers"],
    faq: [
      { question: "Does it alert me before I run out?", answer: "Yes — low-stock and reorder alerts fire before you hit zero." },
      { question: "Can it handle multiple locations?", answer: "Yes — track stock across warehouses and stores." },
      { question: "Does it connect to my store?", answer: "Yes — it can sync with your online store and POS." },
      { question: "Can I manage suppliers and POs?", answer: "Yes — suppliers and purchase orders are built in." },
    ],
    relatedServices: ["online-stores", "admin-dashboards", "crm-systems"],
    jsonLdServiceType: "Inventory Management System Development",
  },
  {
    slug: "hr-systems",
    href: "/services/hr-systems",
    label: "HR Systems",
    category: "CRM & Business Systems",
    headline: "HR Systems That Automate Admin and Keep Your Team Organised",
    subheadline: "Employee records, leave, onboarding, and performance in one place.",
    seoTitle: "Custom HR System Development | Digital Studio LF",
    seoDescription: "Custom HR system development with employee records, leave, payroll data, onboarding, and performance. Automate HR admin.",
    focusKeyword: "custom HR system development",
    secondaryKeywords: ["HR management software development", "custom HRMS development", "employee management system", "leave management software", "HR software for small business"],
    price: null,
    deliveryTime: "28–45 days",
    heroDescription: "Our custom HR system development automates HR admin and keeps your team organised with employee records, leave, onboarding, and performance tracking in one secure place.",
    whatYouGet: ["Employee records", "Leave management", "Payroll data & exports", "Onboarding workflows", "Performance reviews", "Role-based access"],
    useCases: ["Growing businesses", "HR managers", "Multi-location teams", "Agencies", "SMBs"],
    faq: [
      { question: "Does it handle leave and approvals?", answer: "Yes — leave requests, balances, and approval flows are built in." },
      { question: "Can it support onboarding?", answer: "Yes — structured onboarding checklists and documents for new hires." },
      { question: "Is employee data secure?", answer: "Yes — role-based access and secure storage protect sensitive data." },
      { question: "Can it export payroll data?", answer: "Yes — payroll-ready exports for your accountant or payroll provider." },
    ],
    relatedServices: ["employee-portals", "admin-dashboards", "crm-systems"],
    jsonLdServiceType: "HR System Development",
  },

  // ───── BOOKING & RESERVATIONS ─────
  {
    slug: "hotel-booking-systems",
    href: "/services/hotel-booking-systems",
    label: "Hotel Booking Systems",
    category: "Booking & Reservations",
    headline: "Hotel Booking Systems That Take Direct Reservations and Cut OTA Commission",
    subheadline: "Direct bookings, online payment, full control — no OTA fees.",
    seoTitle: "Hotel Booking System Development | Digital Studio LF",
    seoDescription: "Hotel booking system development with availability calendar, online payment, and confirmations. Take direct reservations and cut OTA commission.",
    focusKeyword: "hotel booking system development",
    secondaryKeywords: ["hotel reservation system development", "booking engine for hotel website", "riad booking system Morocco", "direct booking engine development", "availability calendar booking system"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our hotel booking system development lets hotels and riads take direct reservations with an availability calendar and online payment — keeping the commission OTAs would otherwise take.",
    whatYouGet: ["Availability calendar", "Online payment & deposits", "Instant booking confirmation", "Room & rate management", "Guest details capture", "Multilingual support"],
    useCases: ["Hotels", "Riads", "Guesthouses", "Resorts", "Serviced apartments"],
    differentiator: "Direct bookings, no Booking.com commission, and full control of your inventory.",
    faq: [
      { question: "Can guests pay a deposit or in full?", answer: "Yes — flexible payment including deposits, full payment, or pay-on-arrival." },
      { question: "Does it prevent double bookings?", answer: "Yes — the availability calendar updates instantly to prevent overlaps." },
      { question: "Can I manage rooms and rates?", answer: "Yes — manage room types, rates, and seasonal pricing yourself." },
      { question: "Is it multilingual?", answer: "Yes — English, French, and Arabic for international guests." },
    ],
    relatedServices: ["hotel-riad-websites", "crm-for-travel-agencies", "restaurant-reservations"],
    jsonLdServiceType: "Hotel Booking System Development",
  },
  {
    slug: "appointment-booking",
    href: "/services/appointment-booking",
    label: "Appointment Booking",
    category: "Booking & Reservations",
    headline: "Appointment Booking Systems That Fill Your Calendar Automatically",
    subheadline: "Online scheduling with reminders, payments, and calendar sync.",
    seoTitle: "Appointment Booking System Development | Digital Studio LF",
    seoDescription: "Appointment booking system development with online scheduling, reminders, cancellations, payments, and calendar sync. Fill your calendar.",
    focusKeyword: "appointment booking system development",
    secondaryKeywords: ["online appointment scheduling system", "booking system for clinics and salons", "appointment scheduling software development", "booking system with reminders", "calendar booking system development"],
    price: null,
    deliveryTime: "14–28 days",
    heroDescription: "Our appointment booking system development fills your calendar automatically with online scheduling, automated reminders, and payments — cutting no-shows and back-and-forth.",
    whatYouGet: ["Online self-scheduling", "Automated reminders", "Cancellations & rescheduling", "Online payment / deposits", "Calendar sync", "Staff & service management"],
    useCases: ["Clinics", "Salons & spas", "Coaches", "Consultants", "Gyms & studios"],
    faq: [
      { question: "Does it reduce no-shows?", answer: "Yes — automated reminders and optional deposits significantly cut no-shows." },
      { question: "Can clients reschedule themselves?", answer: "Yes — clients can cancel or reschedule within your rules." },
      { question: "Does it sync with my calendar?", answer: "Yes — it syncs with Google/Outlook calendars to avoid conflicts." },
      { question: "Can I take payment at booking?", answer: "Yes — full payment or deposits can be collected at booking." },
    ],
    relatedServices: ["medical-websites", "crm-systems", "landing-pages"],
    jsonLdServiceType: "Appointment Booking System Development",
  },
  {
    slug: "tour-reservations",
    href: "/services/tour-reservations",
    label: "Tour Reservations",
    category: "Booking & Reservations",
    headline: "Tour and Excursion Reservation Systems Built for Travel Businesses",
    subheadline: "Tour catalogs, availability, and online booking with payment.",
    seoTitle: "Tour Reservation System Development | Digital Studio LF",
    seoDescription: "Tour reservation system development with tour catalog, availability, online booking, payment, and client management for travel businesses.",
    focusKeyword: "tour reservation system development",
    secondaryKeywords: ["tour booking system development", "excursion booking website", "activity booking software", "tour operator booking system Morocco", "travel booking platform development"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our tour reservation system development lets tour operators and travel agencies sell excursions online with a tour catalog, real-time availability, payments, and client management.",
    whatYouGet: ["Tour & excursion catalog", "Availability & capacity", "Online booking & payment", "Client management", "Guide / resource scheduling", "Multilingual support"],
    useCases: ["Tour operators", "DMCs", "Travel agencies", "Excursion providers", "Activity companies"],
    faq: [
      { question: "Can I manage capacity per tour?", answer: "Yes — set capacity and availability per date and time slot." },
      { question: "Do customers pay online?", answer: "Yes — secure online payment with instant confirmation." },
      { question: "Can it handle multiple languages?", answer: "Yes — ideal for international travellers in EN/FR/AR." },
      { question: "Does it integrate with a CRM?", answer: "Yes — bookings can flow into a travel CRM for follow-up." },
    ],
    relatedServices: ["crm-for-travel-agencies", "hotel-booking-systems", "crm-systems"],
    jsonLdServiceType: "Tour Reservation System Development",
  },
  {
    slug: "restaurant-reservations",
    href: "/services/restaurant-reservations",
    label: "Restaurant Reservations",
    category: "Booking & Reservations",
    headline: "Restaurant Reservation Systems That Fill Tables and Reduce No-Shows",
    subheadline: "Online reservations with table management and reminders.",
    seoTitle: "Restaurant Reservation System Development | Digital Studio LF",
    seoDescription: "Restaurant reservation system development with online bookings, table management, reminders, and deposits. Fill tables and reduce no-shows.",
    focusKeyword: "restaurant reservation system development",
    secondaryKeywords: ["online table booking system", "restaurant booking software development", "table reservation system Morocco", "restaurant reservation with deposits", "table management software"],
    price: null,
    deliveryTime: "14–28 days",
    heroDescription: "Our restaurant reservation system development fills tables with online bookings, smart table management, and automated reminders that reduce no-shows.",
    whatYouGet: ["Online table reservations", "Table & floor management", "Automated reminders", "Optional deposits", "Guest history", "Multilingual support"],
    useCases: ["Restaurants", "Cafes", "Event dining", "Catering", "Hotel restaurants"],
    faq: [
      { question: "Can guests book a specific time?", answer: "Yes — guests choose available times based on your table capacity." },
      { question: "Does it reduce no-shows?", answer: "Yes — reminders and optional deposits cut no-shows." },
      { question: "Can I manage tables and seating?", answer: "Yes — floor and table management keeps bookings organised." },
      { question: "Is it mobile-friendly?", answer: "Yes — guests book easily from any device." },
    ],
    relatedServices: ["restaurant-websites", "appointment-booking", "crm-systems"],
    jsonLdServiceType: "Restaurant Reservation System Development",
  },
  {
    slug: "event-booking",
    href: "/services/event-booking",
    label: "Event Booking",
    category: "Booking & Reservations",
    headline: "Event Booking Platforms That Sell Tickets and Manage Attendees",
    subheadline: "Ticket sales, attendee management, and check-in in one platform.",
    seoTitle: "Event Booking Platform Development | Digital Studio LF",
    seoDescription: "Event booking platform development with ticket sales, attendee management, payment, check-in, and confirmations. Sell tickets and manage events.",
    focusKeyword: "event booking platform development",
    secondaryKeywords: ["event ticketing platform development", "online ticket sales website", "event registration system development", "ticketing system with QR check-in", "event booking website design"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our event booking platform development lets organisers sell tickets, manage attendees, and handle check-in with payments and automated confirmations in one platform.",
    whatYouGet: ["Ticket sales & tiers", "Attendee management", "Online payment", "QR check-in", "Email confirmations", "Sales dashboard"],
    useCases: ["Event organisers", "Venues", "Conference planners", "Wedding planners", "Workshops"],
    faq: [
      { question: "Can I sell different ticket types?", answer: "Yes — multiple tiers, early-bird pricing, and capacity limits." },
      { question: "How does check-in work?", answer: "Attendees get QR codes scanned at the door for fast check-in." },
      { question: "Do attendees get confirmations?", answer: "Yes — automated email confirmations with tickets." },
      { question: "Can I see sales in real time?", answer: "Yes — a dashboard shows ticket sales and revenue live." },
    ],
    relatedServices: ["appointment-booking", "landing-pages", "crm-systems"],
    jsonLdServiceType: "Event Booking Platform Development",
  },

  // ───── AI & AUTOMATION ─────
  {
    slug: "ai-chatbots",
    href: "/services/ai-chatbots",
    label: "AI Chatbots",
    category: "AI & Automation",
    headline: "AI Chatbots That Answer Client Questions 24/7 and Capture Leads While You Sleep",
    subheadline: "Trained on your content, on your website and WhatsApp.",
    seoTitle: "AI Chatbot Development for Business | Digital Studio LF",
    seoDescription: "AI chatbot development for business — trained on your content, captures leads, handles FAQs, and integrates with WhatsApp and your website.",
    focusKeyword: "AI chatbot development for business",
    secondaryKeywords: ["custom AI chatbot for website", "AI customer support chatbot", "AI chatbot with lead capture", "WhatsApp AI chatbot development", "AI assistant trained on your data"],
    price: null,
    deliveryTime: "14–28 days",
    heroDescription: "Our AI chatbot development for business builds assistants trained on your own content that answer client questions 24/7, capture leads, and hand off to your team when needed.",
    whatYouGet: ["Trained on your content", "Lead capture & qualification", "FAQ & support handling", "WhatsApp & web integration", "Human handoff", "Conversation analytics"],
    useCases: ["Service businesses", "E-commerce", "Hospitality", "Support teams", "Agencies"],
    faq: [
      { question: "What does the chatbot learn from?", answer: "We train it on your website, documents, and FAQs so answers are accurate to your business." },
      { question: "Can it capture leads?", answer: "Yes — it qualifies visitors and captures contact details into your CRM." },
      { question: "Does it work on WhatsApp?", answer: "Yes — it can run on your website and WhatsApp." },
      { question: "Can it hand off to a human?", answer: "Yes — it escalates to your team when needed." },
    ],
    relatedServices: ["whatsapp-automation", "crm-systems", "landing-pages"],
    jsonLdServiceType: "AI Chatbot Development",
  },
  {
    slug: "whatsapp-automation",
    href: "/services/whatsapp-automation",
    label: "WhatsApp Automation",
    category: "AI & Automation",
    headline: "WhatsApp Automation That Follows Up Leads and Closes Sales on Autopilot",
    subheadline: "Automate the channel where your customers actually reply.",
    seoTitle: "WhatsApp Business Automation | Digital Studio LF",
    seoDescription: "WhatsApp business automation with automated replies, lead follow-up, sequences, and CRM integration. Automate your primary sales channel.",
    focusKeyword: "WhatsApp business automation",
    secondaryKeywords: ["WhatsApp Business API integration", "WhatsApp chatbot for business", "automated WhatsApp messages", "WhatsApp CRM integration", "WhatsApp marketing automation Morocco"],
    price: null,
    deliveryTime: "14–28 days",
    heroDescription: "Our WhatsApp business automation follows up leads and closes sales on autopilot with automated replies, sequences, and CRM integration — on the channel where MENA customers actually respond.",
    whatYouGet: ["Automated replies", "Lead follow-up sequences", "Broadcast campaigns", "CRM integration", "Appointment & order updates", "Performance analytics"],
    useCases: ["Moroccan & MENA businesses", "E-commerce", "Real estate", "Travel agencies", "Clinics & salons"],
    differentiator: "In Morocco and MENA, 80%+ of business conversations happen on WhatsApp — we automate yours.",
    faq: [
      { question: "Can it follow up leads automatically?", answer: "Yes — timed sequences nurture leads until they reply or convert." },
      { question: "Does it integrate with my CRM?", answer: "Yes — conversations and leads sync with your CRM." },
      { question: "Can it send order or booking updates?", answer: "Yes — automated confirmations, reminders, and updates." },
      { question: "Is it compliant with WhatsApp rules?", answer: "Yes — we build on the official WhatsApp Business API." },
    ],
    relatedServices: ["ai-chatbots", "crm-systems", "email-automation"],
    jsonLdServiceType: "WhatsApp Automation",
  },
  {
    slug: "workflow-automation",
    href: "/services/workflow-automation",
    label: "Workflow Automation",
    category: "AI & Automation",
    headline: "Workflow Automation That Eliminates Repetitive Tasks and Saves Hours Every Week",
    subheadline: "Connect your tools and let the busywork run itself.",
    seoTitle: "Business Workflow Automation | Digital Studio LF",
    seoDescription: "Business workflow automation with n8n, Zapier, and Make — CRM triggers, email and WhatsApp automation. Eliminate repetitive tasks.",
    focusKeyword: "business workflow automation",
    secondaryKeywords: ["n8n automation agency", "Zapier automation expert", "business process automation services", "Make automation consultant", "API integration and automation"],
    price: null,
    deliveryTime: "14–28 days",
    heroDescription: "Our business workflow automation connects your tools and eliminates repetitive tasks, saving your team hours every week with automated triggers across CRM, email, and messaging.",
    whatYouGet: ["n8n / Zapier / Make workflows", "CRM & app triggers", "Email & WhatsApp automation", "Data sync between tools", "Scheduled jobs", "Error monitoring"],
    useCases: ["Agencies", "Operations teams", "SMBs", "E-commerce", "Sales teams"],
    faq: [
      { question: "Which tools can you connect?", answer: "Most popular apps via n8n, Zapier, or Make, plus custom APIs." },
      { question: "What can be automated?", answer: "Lead routing, data entry, notifications, reporting, follow-ups, and more." },
      { question: "How much time will it save?", answer: "It depends on your processes, but teams commonly recover several hours per week." },
      { question: "Do you monitor for failures?", answer: "Yes — we add error handling and monitoring so automations stay reliable." },
    ],
    relatedServices: ["ai-crm", "email-automation", "crm-systems"],
    jsonLdServiceType: "Workflow Automation",
  },
  {
    slug: "ai-crm",
    href: "/services/ai-crm",
    label: "AI-Powered CRM",
    category: "AI & Automation",
    headline: "AI-Powered CRM Systems That Score Leads, Automate Follow-Ups, and Close More Deals",
    subheadline: "A CRM with AI scoring, smart segmentation, and predictive pipeline.",
    seoTitle: "AI-Powered CRM Development | Digital Studio LF",
    seoDescription: "AI-powered CRM development with lead scoring, AI outreach, smart segmentation, and predictive pipeline. Close more deals with less manual work.",
    focusKeyword: "AI-powered CRM development",
    secondaryKeywords: ["CRM with AI lead scoring", "AI sales automation software", "intelligent CRM development", "predictive sales pipeline software", "AI CRM for sales teams"],
    price: null,
    deliveryTime: "28–60 days",
    heroDescription: "Our AI-powered CRM development adds lead scoring, smart segmentation, and predictive pipeline insights to your CRM so your team focuses on the deals most likely to close.",
    whatYouGet: ["AI lead scoring", "Smart segmentation", "AI-assisted outreach", "Predictive pipeline", "Automated follow-ups", "Reporting & insights"],
    useCases: ["Sales teams", "Agencies", "Growth-stage businesses", "Real estate", "B2B"],
    faq: [
      { question: "How does AI scoring help?", answer: "It ranks leads by likelihood to convert so reps work the best ones first." },
      { question: "Can it draft outreach?", answer: "Yes — AI can suggest and personalise follow-up messages." },
      { question: "Is it built on our data?", answer: "Yes — models use your pipeline data for relevant predictions." },
      { question: "Can it integrate with our stack?", answer: "Yes — it connects to your email, calendar, and tools." },
    ],
    relatedServices: ["crm-systems", "workflow-automation", "email-automation"],
    jsonLdServiceType: "AI CRM Development",
  },
  {
    slug: "email-automation",
    href: "/services/email-automation",
    label: "Email Automation",
    category: "AI & Automation",
    headline: "Email Automation That Nurtures Leads and Drives Revenue on Autopilot",
    subheadline: "Sequences, triggers, and segmentation that sell while you work.",
    seoTitle: "Email Marketing Automation Setup | Digital Studio LF",
    seoDescription: "Email marketing automation setup with sequences, triggers, segmentation, templates, and CRM integration. Nurture leads and drive revenue.",
    focusKeyword: "email marketing automation setup",
    secondaryKeywords: ["email drip campaign setup", "email sequence automation service", "abandoned cart email automation", "email marketing for ecommerce", "automated email follow-up system"],
    price: null,
    deliveryTime: "10–21 days",
    heroDescription: "Our email marketing automation setup builds sequences, triggers, and segmentation that nurture leads and drive revenue automatically — so the right message reaches the right person at the right time.",
    whatYouGet: ["Automated sequences", "Behaviour-based triggers", "List segmentation", "Branded templates", "CRM / store integration", "Performance reporting"],
    useCases: ["E-commerce", "Coaches", "Agencies", "SaaS", "Local businesses"],
    faq: [
      { question: "Which email platforms do you use?", answer: "We work with leading providers and pick the best fit for your needs." },
      { question: "What sequences should I have?", answer: "Typically welcome, nurture, abandoned-cart, and re-engagement — we advise per business." },
      { question: "Can it connect to my store or CRM?", answer: "Yes — triggers fire from store and CRM events." },
      { question: "Do you design the templates?", answer: "Yes — branded, responsive templates are included." },
    ],
    relatedServices: ["crm-systems", "landing-pages", "workflow-automation"],
    jsonLdServiceType: "Email Automation Setup",
  },

  // ───── AUTHENTICATION (custom: login-pages) ─────
  {
    slug: "login-pages",
    href: "/services/login-pages",
    label: "Login Pages",
    category: "Authentication",
    headline: "Secure, Branded Login Pages That Match Your Product and Build User Trust",
    subheadline: "Branded auth UIs with 2FA, SSO, and social login.",
    seoTitle: "Custom Login Page Design & Development | Digital Studio LF",
    seoDescription: "Custom login page development with branded design, 2FA, SSO support, and secure sessions. Match your product and build user trust.",
    focusKeyword: "custom login page development",
    secondaryKeywords: ["login page design service", "authentication UI design", "signup page development", "branded login screen design", "login page with 2FA"],
    price: "From $150",
    deliveryTime: "5–10 days",
    heroDescription: "Our custom login page development delivers secure, branded authentication UIs with 2FA, SSO, and social login that match your product and build user trust from the first screen.",
    whatYouGet: ["Branded login & signup UI", "2FA / OTP support", "SSO & social login", "Password reset flows", "Mobile-responsive design", "Secure session handling"],
    useCases: ["SaaS products", "Web apps", "Portals", "Subscription platforms", "Marketplaces"],
    faq: [
      { question: "Do you support 2FA and SSO?", answer: "Yes — two-factor auth, SSO, and social login can all be included." },
      { question: "Can it match our brand?", answer: "Yes — fully branded to match your product's look and feel." },
      { question: "Is it secure?", answer: "Yes — we follow auth best practices with secure sessions and resets." },
      { question: "How long does it take?", answer: "Login pages typically ship in 5–10 days." },
    ],
    relatedServices: ["user-portals", "auth-systems", "admin-dashboards"],
    jsonLdServiceType: "Login Page Development",
    hasCustomPage: true,
  },
  {
    slug: "user-portals",
    href: "/services/user-portals",
    label: "User Portals",
    category: "Authentication",
    headline: "User Portals That Give Your Clients a Personalised, Branded Experience",
    subheadline: "Accounts, dashboards, and history behind a secure login.",
    seoTitle: "Custom User Portal Development | Digital Studio LF",
    seoDescription: "Custom user portal development with accounts, dashboards, history, file access, and notifications. A personalised, branded experience.",
    focusKeyword: "custom user portal development",
    secondaryKeywords: ["member portal development", "user account area development", "personalised user dashboard", "secure member area for website", "portal development services"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our custom user portal development gives your users a personalised, branded space with accounts, dashboards, history, and file access behind a secure login.",
    whatYouGet: ["User accounts & profiles", "Personalised dashboard", "Activity & history", "File & document access", "Notifications", "Secure authentication"],
    useCases: ["SaaS", "Service businesses", "Agencies", "Subscription platforms", "Education"],
    faq: [
      { question: "How is it different from a customer portal?", answer: "User portals focus on the individual user's personalised experience; both can be combined." },
      { question: "Can users manage their profile?", answer: "Yes — users update details, preferences, and settings themselves." },
      { question: "Is login secure?", answer: "Yes — secure auth with optional 2FA and SSO." },
      { question: "Can it integrate with our systems?", answer: "Yes — it connects to your CRM, billing, or app data." },
    ],
    relatedServices: ["customer-portals", "login-pages", "crm-systems"],
    jsonLdServiceType: "User Portal Development",
  },
  {
    slug: "auth-systems",
    href: "/services/auth-systems",
    label: "Secure Auth Systems",
    category: "Authentication",
    headline: "Secure Authentication Systems with 2FA, SSO, and Role-Based Access",
    subheadline: "Production-grade auth for apps that handle real users.",
    seoTitle: "Secure Authentication System Development | Digital Studio LF",
    seoDescription: "Secure authentication system development with 2FA, SSO/OAuth, role-based access, secure sessions, and audit logs. Production-grade auth.",
    focusKeyword: "secure authentication system development",
    secondaryKeywords: ["OAuth integration service", "SSO implementation service", "two-factor authentication development", "user authentication development", "role-based access control implementation"],
    price: null,
    deliveryTime: "21–35 days",
    heroDescription: "Our secure authentication system development delivers production-grade auth with 2FA, SSO/OAuth, role-based access, and audit logs for any app that handles real user accounts.",
    whatYouGet: ["2FA / MFA", "SSO & OAuth providers", "Role-based access control", "Secure session management", "Audit logs", "Password & recovery flows"],
    useCases: ["SaaS", "Fintech", "Enterprise apps", "Marketplaces", "Any app with accounts"],
    faq: [
      { question: "Which SSO providers do you support?", answer: "Google, Microsoft, and other OAuth/OIDC providers as needed." },
      { question: "Do you implement role-based access?", answer: "Yes — granular roles and permissions control access." },
      { question: "Are there audit logs?", answer: "Yes — auth events are logged for security and compliance." },
      { question: "Can you harden an existing app?", answer: "Yes — we can add or upgrade auth in an existing product." },
    ],
    relatedServices: ["login-pages", "user-portals", "admin-dashboards"],
    jsonLdServiceType: "Authentication System Development",
  },

  // ───── NICHE / SPECIAL (custom: crm-for-travel-agencies; root: web-design-morocco) ─────
  {
    slug: "crm-for-travel-agencies",
    href: "/services/crm-for-travel-agencies",
    label: "CRM for Travel Agencies",
    category: "Niche / Special",
    headline: "Custom CRM Built for Travel Agencies — Manage Clients, Bookings, and Revenue",
    subheadline: "A CRM that speaks travel: itineraries, bookings, and payments.",
    seoTitle: "CRM for Travel Agencies | Digital Studio LF",
    seoDescription: "Custom CRM for travel agencies with client profiles, booking pipeline, payment tracking, automation, and reporting. Built for the travel niche.",
    focusKeyword: "CRM for travel agencies",
    secondaryKeywords: ["travel agency software", "travel CRM with booking pipeline", "tour operator CRM development", "travel agency management system", "CRM for DMCs and tour operators"],
    price: null,
    deliveryTime: "28–60 days",
    heroDescription: "Our CRM for travel agencies manages clients, bookings, and revenue in one system built specifically for the travel niche — itineraries, payment tracking, and automation included.",
    whatYouGet: ["Client & traveller profiles", "Booking pipeline", "Payment & balance tracking", "Itinerary management", "Follow-up automation", "Revenue reporting"],
    useCases: ["Moroccan travel agencies", "European incoming operators", "Tour operators", "DMCs", "OTAs"],
    differentiator: "Real travel-niche expertise — we run pm-travelagency.online and build for how agencies actually work.",
    faq: [
      { question: "Is this built for travel specifically?", answer: "Yes — bookings, itineraries, and payment tracking are designed for travel workflows." },
      { question: "Can it track payments and balances?", answer: "Yes — deposits, balances, and due dates per booking." },
      { question: "Can it automate follow-ups?", answer: "Yes — automated reminders for quotes, balances, and post-trip." },
      { question: "Can we migrate existing client data?", answer: "Yes — we import your existing clients and bookings." },
    ],
    relatedServices: ["tour-reservations", "hotel-booking-systems", "workflow-automation"],
    jsonLdServiceType: "Travel Agency CRM Development",
    hasCustomPage: true,
  },
  {
    slug: "booking-websites-for-hotels",
    href: "/booking-websites-for-hotels",
    hasCustomPage: true,
    label: "Booking Sites for Riads",
    category: "Niche / Special",
    headline: "Direct Booking Websites for Hotels and Riads That Cut OTA Commission",
    subheadline: "Own your bookings and recover the margin OTAs take.",
    seoTitle: "Direct Booking Website for Hotels & Riads | Digital Studio LF",
    seoDescription: "Direct booking website for boutique hotels and riads. Cut Booking.com commission, take direct reservations, and recover your margin.",
    focusKeyword: "direct booking website for boutique hotels",
    secondaryKeywords: ["commission-free hotel booking website", "riad direct booking website", "boutique hotel booking site", "guesthouse booking website design", "hotel website without OTA commission"],
    price: null,
    deliveryTime: "14–21 days",
    heroDescription: "Our direct booking website for boutique hotels and riads lets you take reservations commission-free and recover the 15–20% OTAs take — usually paying for itself in 2–3 months.",
    whatYouGet: ["Direct booking engine", "Room gallery & rates", "Availability calendar", "Online payment", "Multilingual (EN/FR/AR)", "Local + worldwide SEO"],
    useCases: ["Boutique hotels", "Riads", "B&Bs", "Guesthouses", "Small resorts"],
    differentiator: "Stop paying 15–20% to Booking.com — a direct booking site recovers that margin in 2–3 months.",
    faq: [
      { question: "How quickly does it pay for itself?", answer: "By avoiding OTA commission, most properties recoup the cost within 2–3 months." },
      { question: "Can guests book and pay directly?", answer: "Yes — direct booking with secure online payment and confirmation." },
      { question: "Is it multilingual?", answer: "Yes — English, French, and Arabic for international guests." },
      { question: "Will it rank locally?", answer: "We build local + worldwide SEO to attract direct traffic." },
    ],
    relatedServices: ["hotel-booking-systems", "hotel-riad-websites", "crm-for-travel-agencies"],
    jsonLdServiceType: "Direct Booking Website Development",
  },
  {
    slug: "web-developer-for-startups",
    href: "/web-developer-for-startups",
    hasCustomPage: true,
    label: "Web Dev for Startups",
    category: "Niche / Special",
    headline: "Fast, Affordable Web Development for Startups — MVPs to Full Products",
    subheadline: "Direct with the developer. Delivered in 7–21 days.",
    seoTitle: "Remote Web Developer for Startups | Digital Studio LF",
    seoDescription: "Remote web developer for startups — MVPs, landing pages, dashboards, and CRMs delivered fast and built to scale. No agency overhead.",
    focusKeyword: "remote web developer for startups",
    secondaryKeywords: ["MVP development for startups", "startup website developer", "freelance developer for startups", "affordable MVP development", "startup web development agency"],
    price: null,
    deliveryTime: "7–21 days",
    heroDescription: "As a remote web developer for startups, we ship MVPs, landing pages, dashboards, and CRMs fast and built to scale — working directly with founders, with no agency overhead.",
    whatYouGet: ["MVP development", "Landing pages", "Admin dashboards", "Custom CRM", "Scalable architecture", "Fast iteration"],
    useCases: ["Pre-seed & seed startups", "Solo founders", "Technical co-founder gaps", "Product launches", "Investor demos"],
    differentiator: "No agency overhead — you work directly with the developer and ship in 7–21 days.",
    faq: [
      { question: "Can you build an MVP fast?", answer: "Yes — focused MVPs ship in as little as 1–3 weeks." },
      { question: "Will it scale later?", answer: "Yes — we build clean, scalable foundations you can grow on." },
      { question: "Do I work directly with the developer?", answer: "Yes — direct communication, no account managers." },
      { question: "Can you join an existing project?", answer: "Yes — we can extend or improve an existing codebase." },
    ],
    relatedServices: ["landing-pages", "admin-dashboards", "crm-systems"],
    jsonLdServiceType: "Startup Web Development",
  },
  {
    slug: "web-design-morocco",
    href: "/web-design-morocco",
    label: "Web Design Morocco",
    category: "Niche / Special",
    headline: "Web Design Agency in Morocco — Websites, CRMs, and Dashboards Built in Marrakesh",
    subheadline: "Local Marrakesh team. EN/FR/AR. Serving Morocco and worldwide.",
    seoTitle: "Web Design Agency in Morocco | Digital Studio LF",
    seoDescription: "Web design agency in Morocco — websites, CRMs, and dashboards built in Marrakesh. English, French, and Arabic. Local and worldwide.",
    focusKeyword: "web design Morocco",
    secondaryKeywords: ["web design Marrakech", "site web Maroc", "web development agency Morocco", "creation site web Marrakech", "Moroccan web design company", "website designer in Morocco"],
    price: null,
    deliveryTime: "7–21 days",
    heroDescription: "As a web design agency in Morocco based in Marrakesh, we build websites, CRMs, and dashboards in English, French, and Arabic for local businesses and clients worldwide.",
    whatYouGet: ["Custom website design", "CRM & dashboards", "Multilingual (EN/FR/AR)", "Local SEO for Morocco", "Direct booking systems", "Ongoing support"],
    useCases: ["Riads & hotels", "Restaurants", "Travel agencies", "Real estate", "Retail & professional services"],
    differentiator: "Marrakesh-based and multilingual — local presence with EN/FR/AR delivery.",
    faq: [
      { question: "Are you based in Morocco?", answer: "Yes — we're based in Marrakesh and serve clients locally and worldwide." },
      { question: "Do you work in French and Arabic?", answer: "Yes — English, French, and Arabic, including multilingual sites." },
      { question: "What do you build?", answer: "Websites, CRMs, dashboards, booking systems, and automation." },
      { question: "Do you serve clients outside Morocco?", answer: "Yes — we work with clients across Europe and worldwide remotely." },
    ],
    relatedServices: ["hotel-riad-websites", "crm-for-travel-agencies", "business-websites"],
    jsonLdServiceType: "Web Design Agency",
    hasCustomPage: true,
  },

  // ───── ENTERPRISE (custom page; never show a price) ─────
  {
    slug: "enterprise-solutions",
    href: "/services/enterprise-solutions",
    label: "Enterprise Solutions",
    category: "Enterprise",
    headline: "Enterprise-Grade Web Solutions — Custom-Built for Complex Business Needs",
    subheadline: "Multi-system platforms, integrations, and scalable architecture.",
    seoTitle: "Enterprise Web Development Solutions | Digital Studio LF",
    seoDescription: "Enterprise web development for complex needs — multi-role platforms, API integrations, and scalable architecture. Contact us for a custom quote.",
    focusKeyword: "enterprise web development",
    secondaryKeywords: ["enterprise software development", "custom enterprise platform", "enterprise application development", "large-scale web application development", "enterprise system integration"],
    price: null,
    isContactOnly: true,
    deliveryTime: "Custom timeline",
    heroDescription: "Our enterprise web development delivers custom-built platforms for complex business needs — multi-role systems, deep integrations, and scalable architecture, scoped to your requirements.",
    whatYouGet: ["Multi-role platforms", "API & system integrations", "Scalable architecture", "Security & compliance", "Dedicated build team", "Ongoing partnership"],
    useCases: ["Large organisations", "Multi-system projects", "Complex integrations", "Regulated industries", "High-scale platforms"],
    faq: [
      { question: "How much does an enterprise project cost?", answer: "Enterprise projects are scoped individually — contact us for a custom quote based on your requirements." },
      { question: "Can you integrate with our existing systems?", answer: "Yes — we specialise in connecting platforms, APIs, and legacy systems." },
      { question: "Do you handle security and compliance?", answer: "Yes — we build to your security and compliance requirements." },
      { question: "What's the timeline?", answer: "Timelines are scoped per project; we define milestones in the proposal." },
    ],
    relatedServices: ["crm-systems", "admin-dashboards", "workflow-automation"],
    jsonLdServiceType: "Enterprise Web Development",
    hasCustomPage: true,
  },
];

// --- Lookups ---
const bySlug = new Map(servicesContent.map((s) => [s.slug, s]));

export function getServiceContent(slug: string): ServiceContent | undefined {
  return bySlug.get(slug);
}

// Slugs rendered by the dynamic /services/[slug] template:
// every service under /services/ that does NOT already have a hand-built static page.
export function getTemplatedSlugs(): string[] {
  return servicesContent
    .filter((s) => !s.hasCustomPage && s.href.startsWith("/services/"))
    .map((s) => s.slug);
}

export function priceLabel(s: Pick<ServiceContent, "price" | "isContactOnly">): string {
  if (s.isContactOnly || !s.price) return "Contact us";
  return s.price;
}
